### ISSUE TITLE
Optimization Steps do not update `pars` variable

### ISSUE THREAD

**Issue by JulianOestreich90** [Rlag1998/Embedding_Generalization#1]
In the `tutorial_embedding_generalization.ipyb` the return values of the optimizer steps are always the same.  When starting the optimizer you get a warning `/home/user/.local/lib/python3.11/site-packages/pennylane/_grad.py:110: UserWarning: Attempted to differentiate a function with no trainable parameters. If this is unintended, please add trainable parameters via the 'requires_grad' attribute or 'argnum' keyword.`

I tried to add requires_grad=True to the numpy objects in the params array, without any change of behaviour.
i am using Pennylane 0.33.1 and Python 3.11.6.

**Comment by JulianOestreich90** [comment]
I could solve the problem by flattening the `init_pars` list, before passing it to the optimizer. By flattening and reshaping the parameters, you ensure that the optimizer can handle them correctly, and you avoid potential issues with nested structures.  It's a dirty fix, but it may help you if you intend to update the notebook one day.

```python
# Flatten the parameters before passing them to the optimizer
flat_pars = np.concatenate([init_pars_classical.flatten(), init_pars_quantum.flatten()])

# Inside the optimization loop, after the optimizer step
new_flat_pars = optimizer.step(lambda w: cost(reshape_pars(w), A=A_batch, B=B_batch), flat_pars)

# Reshape the parameters back to their original structure
pars = reshape_pars(new_flat_pars)

# Define a helper function to reshape the flat parameters back to the nested structure
def reshape_pars(flat_pars):
    split_index = init_pars_classical.size  # Index at which to split the flat parameters
    new_pars_classical = flat_pars[:split_index].reshape(init_pars_classical.shape)
    new_pars_quantum = flat_pars[split_index:].reshape(init_pars_quantum.shape)
    return [new_pars_classical, new_pars_quantum]
```

**Comment by Rlag1998** [comment]
I found this issue to occur when using versions of pennylane after 0.19.0, with version 0.18.0 the optimizer steps should work properly.

Great suggestion about flattening the parameters, until they fix the library it may have to be an inevitable workaround when working with the latest version of pennylane.
