### ISSUE TITLE
Generalization performance only arises from the linear Layer

### ISSUE THREAD

**Issue by JulianOestreich90** [Rlag1998/Embedding_Generalization#2]
As i understood from your paper the reason for using a classical dense linear layer before the trainable Quantum Embedding is Feature Extraction. Why were you still using this linear layer, when you worked with a PCA reduced Dataset with just 2 Features? 

When i worked with your model on the Breast Cancer Dataset, i had the feeling that the training mainly happened within the Linear Layer. Deleting the Linear Layer and optimizing only the quantum part of your model on a 2-dimensional PCA reduced dataset, confirmed my feeling. I also carried out the experiments with 4 Features and a double no. of qubits, but there was still no training effect in the quantum embeddings.

I tried also different batch sizes, different learning rates, various optimizers and scaling the features between [0, 2*pi).

**Comment by Rlag1998** [comment]
The linear layer is still required for training. To benchmark the training that occurs within the quantum feature map, you can vary its complexity, depth or number of parameters then compare the results.
